const generateId = () => {
  const head = Date.now().toString(36);
  const tail = Math.random().toString(36).slice(2);
  return head + tail;
};

// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
  {
    cnpj: '20.001.001/0001/22',
    cidade: 'rio de janeiro',
    uf: 'rj',
    cep: '25515-090',
    abertura: '02/01/2021',
    id: generateId(),
    rua: 'Rua Qualquer',
    numero: 10,
    complemento: 'perto de',
    bairro: 'sjm',
    tipoDeDoc: 'cpf',
    razaoSocialOuNome: 'ola sa',
    email:'teste@teste.com',

  },
];
